##############################################################
####################         Layout       ####################
##############################################################
styleEntry: 'dist.scss' # entry style file that contains all styles needed
sidebarBg: 'img/side.jpg' # a dark tone image is recommended
useBack: true # when in non-index pages, hide all header and show the 'Back' link pointing to index page.

##############################################################
##################         Index page        #################
##############################################################

postPerPage: 5 # maximum number of posts displayed per a page

# specify what links do you want the header of the page have, the name of the link will be the key, e.g. About
# Put relative path (start with '/') if you want a new page, or absolute path if you want a redirect. EJS file
# of the new page should be in the root of view folder.
header:
  About: '/about'



##############################################################
##################         Post page         #################
##############################################################

autoComment: false # display disqus comment by default (note that disqus not accessible in China)

# share icons that you want to display beside your posts. See http://overtrue.me/share.js/ for details.
share:
  - 'qq'
  - 'wechat'
  - 'qzone'
  - 'weibo' # Sina Weibo
  # - 'tencent' # Tencent Weibo
  # - 'douban'
  # - 'diandian'
  - 'facebook'
  - 'twitter'
  # - 'linkedin'
  # - 'google' # Google+
